### ISSUE TITLE
Windows Defender flags YARC-launcher as Trojan:Script/Wacatac.H!ml

### ISSUE THREAD

**Issue by TGiles** [YARC-Official/YARC-Launcher#21]
[VirusTotal seems to give a couple hits as well](https://www.virustotal.com/gui/file/4262a9da774fe3398d0c3840ea5d3b60340bace378cfb335f03ee9a3b9c5d555?nocache=1) but wanted to raise the issue just so yall are aware. I have no idea how you could get the false positives to go away though. Might need to put some disclaimer text with the releases so people are aware 🙂

**Comment by TGiles** [comment]
Agreed, I figured it was something as straightforward like what you posted. I'm not in the discord so apologies for making you have to respond to the same questions again! Yeah, I'd prefer if the code wasn't obfuscated as well. Feel free to close in that case, just wanted to bring it up just in case. Thanks!

**Comment by EliteAsian123** [comment]
The GitHub gist is to do with tauri's auto update thing actually. We can provide any domain though, so it should be good.

> Another problem is the creation of an .exe by the program

Isn't that... Just what an installer does?

**Comment by EliteAsian123** [comment]
The four still show up, but the others seem to be good now
![image](https://github.com/YARC-Official/YARC-Launcher/assets/29520859/2099fef6-6e3e-45f1-add6-156177d2c0c3)

**Comment by EliteAsian123** [comment]
Hmm yeah, perhaps using an MSI instead of a NSIS is a better idea... I'll look into it tonight!

**Comment by EliteAsian123** [comment]
![image](https://github.com/YARC-Official/YARC-Launcher/assets/29520859/df23c4cc-dd5e-4f69-a407-1c1dfbd88151)
Now some other things have popped up, but at least it's a zero now!

**Comment by TGiles** [comment]
Just downloaded v0.1.3 and didn't get any additional yelling from Defender (other than the SmartScreen). Also didn't get any yelling from MalwareBytes, just as a fyi. Thanks for the quick turnaround!

**Comment by EliteAsian123** [comment]
NICE! I'll close this issue for now then. Thanks for all of the help!
