### ISSUE TITLE
YARG not correctly installed on Linux

### ISSUE THREAD

**Issue by Duder963** [YARC-Official/YARC-Launcher#22]
By default, The launcher can't launch YARG once installed, giving a file not found error. Renaming `YARG.x86_64` to `YARG` fixes that, but leads to a permission error as the executable is not marked as executable. Once both are done, YARG works as expected

**Comment by EliteAsian123** [comment]
Thanks for letting us know. I'll do a quick fix for the first, and look into the second tomorrow or later today when I have time. Apologies for the inconvience!

**Comment by EliteAsian123** [comment]
Fixed in the newest update
