### ISSUE TITLE
"Invalid Drive" error when re-installing YARC

### ISSUE THREAD

**Issue by LaeMat** [YARC-Official/YARC-Launcher#32]
Windows 10 64-bit
Hello. Recently, a drive in my computer corrupted, and I want to play YARG again. I downloaded the latest version of the YARC launcher, only to be thrown the error "Invalid Drive D:\". That is the drive that is no longer in my computer. I tried uninstalling it via Control Panel, only for it to show the same error and not install. I went as far as using a third-party uninstaller which goes as deep as the registry, and yet YARC still throws the same exact error. I even went through my entire drive to remove any YARG/YARC files, and the same thing happens. What can I do?

**Comment by EliteAsian123** [comment]
Hello!

For now, you must manually delete the launcher settings file. This can be accessed in `%userprofile%\AppData\Local\YARC` on windows. Deleting the "Launcher" folder should do the trick!

I'm planning on rewriting the launcher to prevent things like this, but I'm busy with YARG itself right now, unfortunately.

**Comment by LaeMat** [comment]
> Hello!
> 
> For now, you must manually delete the launcher settings file. This can be accessed in `%userprofile%\AppData\Local\YARC` on windows. Deleting the "Launcher" folder should do the trick!
> 
> I'm planning on rewriting the launcher to prevent things like this, but I'm busy with YARG itself right now, unfortunately.

That directory has already been removed. I found another named `in.yarg.launcher`, but removing it still doesn't fix the issue.

**Comment by EliteAsian123** [comment]
Very odd. Can you send a screenshot of the error?

**Comment by LaeMat** [comment]
> Very odd. Can you send a screenshot of the error?

![image](https://github.com/YARC-Official/YARC-Launcher/assets/87903194/7ae4749a-24c7-475b-b555-4956a65f9314)
![image](https://github.com/YARC-Official/YARC-Launcher/assets/87903194/ffd06169-cd03-4b2b-bf73-9e09e5cc42a2)

**Comment by EliteAsian123** [comment]
OH, you mean in the installer, not the launcher? My bad. 

In that case, I'm not too sure what causes that. We use Tauri's installer system, so it's most likely a problem with that. I apologize.

I'm assuming some files are being saved by the msi installer somewhere, but I'm not too sure where they could possibly be. I can look into it.

**Comment by EliteAsian123** [comment]
I found [this Epic Games help page](https://www.epicgames.com/help/en-US/epic-games-store-c5719341124379/launcher-support-c5719357217435/what-do-i-do-if-i-receive-the-error-invalid-drive-when-installing-the-epic-games-launcher-a5720229828379) which could help. They also seem to use the `.msi` installer, so it may work in your case.

**Comment by LaeMat** [comment]
> I found [this Epic Games help page](https://www.epicgames.com/help/en-US/epic-games-store-c5719341124379/launcher-support-c5719357217435/what-do-i-do-if-i-receive-the-error-invalid-drive-when-installing-the-epic-games-launcher-a5720229828379) which could help. They also seem to use the `.msi` installer, so it may work in your case.

I tried using a USB I had labled with the D directory, and it allowed the launcher to run. This doesn't seem like an issue that has been mentioned to NSIS (what seems to be what Tauri uses for their installer?).

**Comment by EliteAsian123** [comment]
Glad you got it figured out! The launcher uses the WiX Toolset v3 instead of the default NSIS installer because NSIS installers frequently get flagged as viruses.

**Comment by EliteAsian123** [comment]
Closing this for now
