### ISSUE TITLE
Multi keybinds?

### ISSUE THREAD

**Issue by Thoughtprovoker** [YARC-Official/YARC-Launcher#37]
Would like to request the option to bind several hotkeys to the same functions. Coming from Phase Shift, drum pads were bound to letter keys as well as the numpad, enabling rapid blasting of the same pad without having your fingers compete for the same tiny space on the keyboard.

**Comment by jgoyvaerts** [comment]
This is already possible in the latest nightly build. You can download the nightly build through the launcher.

Also, you made this issue in the launcher repository, which is intended for issues with the launcher itself. For issues with the game, head over to https://github.com/YARC-Official/YARG

**Comment by Thoughtprovoker** [comment]
I see, my bad.
