### ISSUE TITLE
YARG won't launch from YARC on Steam Deck in ~/Applications

### ISSUE THREAD

**Issue by Soundtoxin** [YARC-Official/YARC-Launcher#39]
This launcher really complicates things but I'm trying to make it work. I had the game running fine but on an old version. I think I was launching the appimage from my Downloads dir before. I want to [integrate with appimagelauncher](https://www.reddit.com/r/SteamDeck/comments/t9xwte/how_to_automatically_integrate_appimage_apps_into/) which makes shortcuts for appimages automatically so that things show up in the "add non-steam game" list. The end goal being I have YARG playable from Game Mode without having to go into Desktop Mode, and ideally being able to update it and have it keep working.
So currently I've got the YARC Launcher v0.3.0 added as a non-steam game with TARGET set to `/home/deck/Applications/yarc-launcher_0.3.0_amd64.AppImage` and START IN set to `/home/deck/Applications`. I launch the game from Desktop Mode and the launcher appears fine. I select YARG on the left side and click Play Stable. I get a FATAL ERROR.
```
Failed to start YARG. Is it installed?\nOs { code: 13, kind: PermissionDenied, message: \"Permission denied\"
```
I've been able to set up similar appimage non-steam games like the Slippi Launcher this way, so not really sure what the problem is. The appimage file has executable permissions for all users.

```
-rwxr-xr-x  1 deck deck  81M Jan  2 03:10 yarc-launcher_0.3.0_amd64.AppImage
```

It would be nice if there were a flatpak available that could be updated along with everything else on my system instead of this built-in updater and appimage files that have the version in the filename so that every update breaks them as non-steam games

**Comment by EliteAsian123** [comment]
The fatal error should only be a thing on the stable version on Linux, and will be fixed with the release of v0.12. For now, nightly should work just fine.

As for the flatpak part, the auto-update feature is from Tauri (a library we use to make the launcher) which unfortunately requires a appimage to work correctly. Not much we can do about that, sorry.
