### ISSUE TITLE
YARC Launcher shows up as blank white in SteamOS Game Mode

### ISSUE THREAD

**Issue by Soundtoxin** [YARC-Official/YARC-Launcher#42]
Spinning this off from https://github.com/YARC-Official/YARC-Launcher/issues/41#issuecomment-1898279063 since my problem was apparently unrelated, pasting and slightly editing my existing comment from the other issue.

When I launch YARC Launcher from SteamOS's Game Mode (which is using the **[Gamescope](https://github.com/ValveSoftware/gamescope) Wayland compositor**) on my Steam Deck it shows up as a blank white window and I can't seem to do anything*. It launches fine in Desktop Mode (KDE Plasma, and according to `echo $XDG_SESSION_TYPE` output, Desktop Mode is running Plasma in X11 mode rather than also being Wayland). My workaround for now is to launch the executables for Stable or Nightly that the launcher downloaded directly. I can add those as non-Steam games and they play fine in Game Mode. The downside being that if they ever get updated I need to go into Desktop Mode to get the launcher open and fetch a new version.

*I have actually noticed if I move my mouse cursor around that the cursor icon changes in certain spots. I suspect when hovering buttons that I can't see it's changing as it would normally. Perhaps if you knew well where every button is you could actually update or launch the game this way. I may experiment with this more later.

**Comment by Soundtoxin** [comment]
Nice, confirmed that workaround works. Added to the launch options on Steam in the game's properties as `WEBKIT_DISABLE_COMPOSITING_MODE=1 %command%`.

**Comment by EliteAsian123** [comment]
Closing as a solution was found
