### ISSUE TITLE
Portable Version

### ISSUE THREAD

**Issue by VocalFan** [YARC-Official/YARC-Launcher#44]
Include a way to have a Portable version of the Launcher, this would allow USB based installs.

**Comment by EliteAsian123** [comment]
Sorry for the late reply.

Unfortunately, portable versions don't really work well with the whole installation system we have setup, along with the launcher's auto-update system.

For this, I'd just recommend using a portable version of YARG or just transporting the installer around. The launcher is kinda designed to be a more "permanent" if you will, solution.
