### ISSUE TITLE
Not launching on Linux Mint

### ISSUE THREAD

**Issue by asimard1** [YARC-Official/YARC-Launcher#45]
When I launch YARC launcher, the launcher does not load at all. There is a window that appears on my panel, but it does not do anything and it appears to be frozen.

![image](https://github.com/YARC-Official/YARC-Launcher/assets/58919185/e08ca3d2-6957-4616-a40e-d29d1f0dd2b0)

I had some problems with xapp in the last couple days and I was able to "force" its installation, but now it still will not launch. I used to have the error "Failed to load module "xapp-gtk3-module"." and then it froze, but now all I get in the terminal is "[2024-05-27][03:23:43][DEBUG][reqwest::connect] starting new connection: https://releases.yarg.in/" and it doesn't do anything.

**Comment by asimard1** [comment]
Update: the launcher only works if I run it as root. Is there a way to not have to do this?

I can send more information if you want; I am unsure how to find any more info.

**Comment by EliteAsian123** [comment]
Sorry for the late reply,

Unfortunately, I'm not quite sure as I'm not too familiar with Linux. Does this still occur on v1.0.0 of the launcher?

Thanks!

**Comment by EliteAsian123** [comment]
Glad you got it figured out!
