### ISSUE TITLE
Setting launch options

### ISSUE THREAD

**Issue by ggtylerr** [YARC-Official/YARC-Launcher#47]
Adding a way to configure launch options (i.e. the feature from Steam where you can add some environment variables and whatnot) would be really nice, especially for Linux users - just as an example, if you're on a laptop with two GPUs (integrated and discrete) you'll need to pass the env variable `DRI_PRIME=1` for the game to use your dGPU (and not run at 3fps.) Could also be useful for passing something like mangohud and debug flags.

**Comment by EliteAsian123** [comment]
Sorry for the late reply.

Yes, this is planned in the rewrite of the launcher!

**Comment by EliteAsian123** [comment]
This has been added to the v1.0.0 release of the launcher!
