### ISSUE TITLE
Fatal error with new launcher

### ISSUE THREAD

**Issue by VWO2482** [YARC-Official/YARC-Launcher#53]
![image](https://github.com/user-attachments/assets/f48d55af-3a9b-4e52-8a89-44b954c7ca88)
I updated the launcher, but must have moved its location to the wrong place and could not open this properly. I uninstalled and reinstalled the launcher twice and this same error came back.

**Comment by EliteAsian123** [comment]
Issue solved in Discord:

The user reported that running the launcher in administrator mode fixed the problem.
