### ISSUE TITLE
Launcher Unable to Connect to Internet Despite Having Internet Connection

### ISSUE THREAD

**Issue by FroggMaster** [YARC-Official/YARC-Launcher#54]
## The Problem 

When I launch the latest version of YARC 1.0.0; The Launcher is unable to connect to the internet. I've included a  screenshot where you can see the YARC Launcher showing an error. In the Windows task bar you can see I'm connected to the internet VIA Ethernet. 
![image](https://github.com/user-attachments/assets/e295d42d-1f15-4315-bdfd-30c1bcd15640)

## My System Information / YARC Launcher Version
**OS:** Windows 11 64bit 
**Internet Connection Method:** Ethernet
**YARC  Version:** 1.0.0 (Latest Available) 

## What I've Tried
- I've already following the instructions from: https://docs.yarg.in/en/launcher and attempted to repair the install for "Microsoft Edge WebView2 Runtime”. 
- I have completely uninstalled and reinstalled "Microsoft Edge WebView2 Runtime”. 
- I've also attempted to reinstall the launcher multiple times. 
- I'm using Windows Defender and it shows no signs of blocking YARC Launcher. 
- I attempted disabling Windows Defender / Windows Firewall and the issue persists 
- I've tried using Wifi instead of Ethernet, the issue persists regardless of my connection method. 
- ALL other applications are able to connect to the internet without issues. 

## Workaround 
- If I use YARC Version 0.3.1 the launcher works and is able to connect to the internet without any issues.

**Comment by EliteAsian123** [comment]
Hello, thanks for the report! The latest update should've fixed this issue. If the issue persists or you discover another issue, please feel free to make a new issue!

Thanks!

**Comment by FroggMaster** [comment]
I can confirm that the issue has been resolved in the latest launcher release. 🐸 Thank you for such a timely fix!
